package server

import "github.com/alecthomas/chroma/v2/styles"
import "github.com/alecthomas/chroma/v2"

var Catppuccin = styles.Register(chroma.MustNewStyle("catppuccin", chroma.StyleEntries{
	chroma.Background:               "bg:#24273a #cad3f5",
	chroma.CodeLine:                 "#cad3f5",
	chroma.Error:                    "#ed8796",
	chroma.Other:                    "#cad3f5",
	chroma.LineTableTD:              "",
	chroma.LineTable:                "",
	chroma.LineHighlight:            "bg:#494d64",
	chroma.LineNumbersTable:         "#8087a2",
	chroma.LineNumbers:              "#8087a2",
	chroma.Keyword:                  "#c6a0f6",
	chroma.KeywordReserved:          "#c6a0f6",
	chroma.KeywordPseudo:            "#c6a0f6",
	chroma.KeywordConstant:          "#f5a97f",
	chroma.KeywordDeclaration:       "#ed8796",
	chroma.KeywordNamespace:         "#8bd5ca",
	chroma.KeywordType:              "#ed8796",
	chroma.Name:                     "#cad3f5",
	chroma.NameClass:                "#eed49f",
	chroma.NameConstant:             "#eed49f",
	chroma.NameDecorator:            "bold #8aadf4",
	chroma.NameEntity:               "#8bd5ca",
	chroma.NameException:            "#f5a97f",
	chroma.NameFunction:             "#8aadf4",
	chroma.NameFunctionMagic:        "#8aadf4",
	chroma.NameLabel:                "#91d7e3",
	chroma.NameNamespace:            "#f5a97f",
	chroma.NameProperty:             "#f5a97f",
	chroma.NameTag:                  "#c6a0f6",
	chroma.NameVariable:             "#f4dbd6",
	chroma.NameVariableClass:        "#f4dbd6",
	chroma.NameVariableGlobal:       "#f4dbd6",
	chroma.NameVariableInstance:     "#f4dbd6",
	chroma.NameVariableMagic:        "#f4dbd6",
	chroma.NameAttribute:            "#8aadf4",
	chroma.NameBuiltin:              "#91d7e3",
	chroma.NameBuiltinPseudo:        "#91d7e3",
	chroma.NameOther:                "#cad3f5",
	chroma.Literal:                  "#cad3f5",
	chroma.LiteralDate:              "#cad3f5",
	chroma.LiteralString:            "#a6da95",
	chroma.LiteralStringChar:        "#a6da95",
	chroma.LiteralStringSingle:      "#a6da95",
	chroma.LiteralStringDouble:      "#a6da95",
	chroma.LiteralStringBacktick:    "#a6da95",
	chroma.LiteralStringOther:       "#a6da95",
	chroma.LiteralStringSymbol:      "#a6da95",
	chroma.LiteralStringInterpol:    "#a6da95",
	chroma.LiteralStringAffix:       "#ed8796",
	chroma.LiteralStringDelimiter:   "#8aadf4",
	chroma.LiteralStringEscape:      "#8aadf4",
	chroma.LiteralStringRegex:       "#8bd5ca",
	chroma.LiteralStringDoc:         "#6e738d",
	chroma.LiteralStringHeredoc:     "#6e738d",
	chroma.LiteralNumber:            "#f5a97f",
	chroma.LiteralNumberBin:         "#f5a97f",
	chroma.LiteralNumberHex:         "#f5a97f",
	chroma.LiteralNumberInteger:     "#f5a97f",
	chroma.LiteralNumberFloat:       "#f5a97f",
	chroma.LiteralNumberIntegerLong: "#f5a97f",
	chroma.LiteralNumberOct:         "#f5a97f",
	chroma.Operator:                 "bold #91d7e3",
	chroma.OperatorWord:             "bold #91d7e3",
	chroma.Comment:                  "italic #6e738d",
	chroma.CommentSingle:            "italic #6e738d",
	chroma.CommentMultiline:         "italic #6e738d",
	chroma.CommentSpecial:           "italic #6e738d",
	chroma.CommentHashbang:          "italic #6e738d",
	chroma.CommentPreproc:           "italic #6e738d",
	chroma.CommentPreprocFile:       "bold #6e738d",
	chroma.Generic:                  "#cad3f5",
	chroma.GenericInserted:          "bg:#363a4f #a6da95",
	chroma.GenericDeleted:           "#ed8796 bg:#363a4f",
	chroma.GenericEmph:              "italic #cad3f5",
	chroma.GenericStrong:            "bold #cad3f5",
	chroma.GenericUnderline:         "underline #cad3f5",
	chroma.GenericHeading:           "bold #f5a97f",
	chroma.GenericSubheading:        "bold #f5a97f",
	chroma.GenericOutput:            "#cad3f5",
	chroma.GenericPrompt:            "#cad3f5",
	chroma.GenericError:             "#ed8796",
	chroma.GenericTraceback:         "#ed8796",
}))
